version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-transformer-remark
    versions:
    - 4.0.0
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 5.0.0
  - dependency-name: netlify-cms-app
    versions:
    - 2.14.32
    - 2.14.33
    - 2.14.34
    - 2.14.35
    - 2.14.37
    - 2.14.40
    - 2.14.46
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: gatsby-cli
    versions:
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.11.1
  - dependency-name: react-icons
    versions:
    - 4.2.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: gatsby
    versions:
    - 2.32.11
  - dependency-name: gatsby-plugin-netlify-cms
    versions:
    - 4.10.0
  - dependency-name: immer
    versions:
    - 8.0.4
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: elliptic
    versions:
    - 6.5.4
